version: 1.0.{build}
build:
  verbosity: minimal
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./SportsStore/SportsStore.csproj --verbosity m
build_script:
  # output will be in ./SportsStore/bin/debug/netcoreapp2.0/publish
  - cmd: dotnet publish ./SportsStore/SportsStore.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: '\SportsStore\bin\Debug\netcoreapp2.0\publish'
   name: WebSite
   type: WebDeployPackage
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./SportsStore.Tests/SportsStore.Tests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd SportsStore.Tests
  - cmd: dotnet xunit
on_finish :
  # any cleanup in here
deploy: off